{{- if .Values.ingress.enabled -}}
{{- $fullName := include "carddavmate.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $middlewares := default (list) .Values.ingress.traefikMiddlewares -}}
{{- if .Values.ingress.stripPrefixes -}}
{{- $middlewares = append $middlewares (printf "%s-%s-slash@kubernetescrd" .Release.Namespace $fullName) -}}
{{- $middlewares = append $middlewares (printf "%s-%s-stripprefix@kubernetescrd" .Release.Namespace $fullName) -}}
{{- end -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "carddavmate.labels" . | nindent 4 }}
  {{- if or .Values.ingress.annotations $middlewares }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with $middlewares }}
    traefik.ingress.kubernetes.io/router.middlewares: {{ join "," . | quote }}
    {{- end }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType | default "Prefix" }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
          {{- end }}
    {{- end }}
{{- end }}
